name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i ${{secrets.SSH_PRIVATE_KEY}} $USERNAME@$SERVER 'rm -rf /var/www/html/*'
        scp -i ${{secrets.SSH_PRIVATE_KEY}} -r ./* $USERNAME@$SERVER:/var/www/html/