name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key file
      run: echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i $SSH_PRIVATE_KEY $USERNAME@$SERVER 'rm -rf /var/www/html/*'
        scp -i $SSH_PRIVATE_KEY -r ./ $USERNAME@$SERVER:/var/www/html/