name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and Add server to known_hosts
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i private_key $USERNAME@$SERVER 'rm -rf /var/www/html/*'
        scp -i private_key -r ./* $USERNAME@$SERVER:/var/www/html/